# Uncomment the next line to define a global platform for your project
source 'https://github.com/StrumElin/MyCocoapods.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'QTModuleIM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

    pod 'RongCloudIM/IMLib', '~> 2.8.3'
    pod 'RongCloudIM/IMKit', '~> 2.8.3'
    pod 'FLAnimatedImage'
    pod 'MJExtension'
    pod 'SDWebImage'
    
    pod 'QTModuleNetwork','0.0.2'
    pod 'QTModuleUtils','0.0.2'
    
  # Pods for QTModuleIM

end
